# Generated by Django 3.0.4 on 2020-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='profile/'),
        ),
    ]
