# Generated by Django 3.0.4 on 2020-03-25 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20200325_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(max_length=7, unique=True, validators=[
                django.core.validators.RegexValidator(message='Invalid Registration Number',
                                                      regex='[a-zA-Z]{2}[0-9]{5}')],
                                   verbose_name='Registration number'),
        ),
    ]
