# Generated by Django 3.0.7 on 2020-09-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_college_abbreviation'),
        ('accounts', '0003_auto_20200906_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.College', verbose_name='College'),
        ),
    ]
