# Generated by Django 3.0.4 on 2020-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20200325_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='profile/'),
        ),
    ]
