# Generated by Django 3.0.4 on 2020-09-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200908_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_number',
        ),
    ]
