# Generated by Django 3.0.4 on 2020-09-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200910_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_number',
        ),
    ]
