# Generated by Django 3.0.4 on 2020-03-29 10:48

import content.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=30, unique=True)),
                ('duration', models.IntegerField(default=4)),
                ('no_of_semesters', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Paper_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Note_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=30, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('note_pdf', models.FileField(blank=True, default=None, null=True, upload_to=content.models.get_note_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subject', verbose_name='Subject')),
                ('upvotes', models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Paper',
            fields=[
                ('paper_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('batch_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('exam', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('T', 'Theory'), ('P', 'Practical')], default='T', max_length=1)),
                ('paper_pdf', models.FileField(blank=True, default=None, null=True, upload_to=content.models.get_paper_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subject', verbose_name='Subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('image', models.ImageField(default='download.jpg', upload_to='books/')),
                ('flink', models.CharField(blank=True, max_length=300)),
                ('alink', models.CharField(blank=True, default='', max_length=300)),
                ('slug', models.SlugField(editable=False, max_length=30, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subject', verbose_name='Subject')),
            ],
        ),
    ]
