# Generated by Django 3.0.4 on 2020-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
