# Generated by Django 3.0.7 on 2020-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
        ),
    ]
