# Generated by Django 3.0.7 on 2020-09-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_college_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.College', verbose_name='College'),
        ),
    ]
