# Generated by Django 3.0.7 on 2020-09-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_note_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.College', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='exam_paper',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.College', verbose_name='College'),
        ),
    ]
