# Generated by Django 3.0.4 on 2020-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0005_auto_20200326_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
