# Generated by Django 3.0.4 on 2020-09-10 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_auto_20200909_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
