# Generated by Django 3.0.4 on 2020-03-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200326_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('image', models.ImageField(default='download.jpg', upload_to='books/')),
                ('flink', models.CharField(blank=True, max_length=300)),
                ('alink', models.CharField(blank=True, default='', max_length=300)),
                ('slug', models.SlugField(editable=False, max_length=30, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subject', verbose_name='Subject')),
            ],
        ),
    ]
