# Generated by Django 3.0.4 on 2020-03-28 07:34

import content.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_auto_20200326_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Paper',
            fields=[
                ('paper_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('batch_year', models.DateField()),
                ('semester', models.IntegerField()),
                ('exam', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('T', 'Theory'), ('P', 'Practical')], default='T', max_length=1)),
                ('paper_pdf', models.FileField(blank=True, default=None, null=True, upload_to=content.models.get_paper_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='Course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subject', verbose_name='Subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
        ),
    ]
