# Generated by Django 3.0.4 on 2020-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_exam_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_semesters',
            field=models.IntegerField(default=8, max_length=2),
        ),
    ]
