# Generated by Django 3.0.4 on 2020-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0008_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='flink',
            field=models.CharField(max_length=300),
        ),
    ]
