# Generated by Django 3.0.4 on 2020-09-12 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20200910_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='alink',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='blog_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='reports',
            field=models.ManyToManyField(related_name='book_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam_paper',
            name='reports',
            field=models.ManyToManyField(related_name='paper_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='blog_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
