# Generated by Django 3.0.4 on 2020-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200328_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
