# Generated by Django 3.0.4 on 2020-03-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0009_auto_20200328_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='alink',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
