# Generated by Django 3.0.4 on 2020-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200912_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
