# Generated by Django 3.0.4 on 2020-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_paper_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_of_semesters',
            field=models.IntegerField(default=8),
        ),
    ]
