# Generated by Django 3.0.4 on 2020-09-12 11:23

import content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_type',
            field=models.CharField(choices=[('L', 'Link'), ('P', 'PDF')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to=content.models.get_book_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
