# Generated by Django 3.0.4 on 2020-03-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0011_auto_20200328_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='flink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(editable=False, max_length=30, unique=True),
        ),
    ]
