# Generated by Django 3.0.4 on 2020-03-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200328_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper_Count',
            new_name='Exam_Paper_Count',
        ),
    ]
