# Generated by Django 3.0.4 on 2020-03-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20200328_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_paper',
            name='batch_year',
            field=models.IntegerField(),
        ),
    ]
